# Generated by Django 5.0.6 on 2024-07-24 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HM1', '0005_alert_dismissed_at_alert_is_dismissed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='after_image',
            field=models.ImageField(blank=True, null=True, upload_to='alerts/images/'),
        ),
        migrations.AddField(
            model_name='alert',
            name='before_image',
            field=models.ImageField(blank=True, null=True, upload_to='alerts/images/'),
        ),
    ]
