# Generated by Django 5.0.6 on 2024-07-26 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HM1', '0006_alert_after_image_alert_before_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='after_image',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='before_image',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='dismissed_at',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='resolved_at',
        ),
        migrations.AlterField(
            model_name='alert',
            name='alert_type',
            field=models.CharField(choices=[('device', 'Device'), ('storage', 'Storage'), ('camera', 'Camera')], max_length=50),
        ),
    ]
