# Generated by Django 5.1 on 2024-08-14 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HM1', '0007_remove_alert_after_image_remove_alert_before_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='alert_type',
            field=models.CharField(choices=[('camera_offline', 'Camera Offline'), ('nvr_dvr_offline', 'NVR/DVR Offline'), ('hdd_abnormal', 'HDD Abnormal'), ('time_mismatch', 'Time Mismatch'), ('recording_less_than_45_days', 'Recording Less Than 45 Days')], max_length=50),
        ),
    ]
