# Generated by Django 5.1 on 2024-08-14 14:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HM1', '0008_alter_alert_alert_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alert',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='alert',
            name='alert_type',
            field=models.CharField(choices=[('camera_offline', 'Camera Offline'), ('nvr_dvr_offline', 'NVR/DVR Offline'), ('hdd_abnormal', 'HDD Abnormal'), ('time_mismatch', 'Time Mismatch'), ('recording_less_than_45_days', 'Recording Less Than 45 Days'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='alert',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
