# Generated by Django 5.1 on 2024-08-16 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HM1', '0009_alter_alert_options_alter_alert_alert_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alert',
            options={},
        ),
        migrations.AlterField(
            model_name='alert',
            name='alert_type',
            field=models.CharField(choices=[('device', 'Device'), ('storage', 'Storage'), ('camera', 'Camera')], max_length=50),
        ),
        migrations.AlterField(
            model_name='alert',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
