# Generated by Django 5.1 on 2024-08-16 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HM1', '0010_alter_alert_options_alter_alert_alert_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='alert_type',
            field=models.CharField(choices=[('camera', 'Camera Offline'), ('nvr_dvr', 'NVR/DVR Offline'), ('hdd', 'HDD Abnormal'), ('time_mismatch', 'Time Mismatch'), ('recording', 'Less Recording')], max_length=50),
        ),
    ]
