# Generated by Django 5.1 on 2024-08-19 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HM1', '0011_alter_alert_alert_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('device_url', models.URLField()),
                ('storage_url', models.URLField()),
                ('camera_url', models.URLField()),
                ('ports_url', models.URLField()),
                ('recording_url', models.URLField()),
                ('site_type', models.CharField(choices=[('dvr', 'DVR'), ('nvr', 'NVR')], max_length=50)),
                ('client', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
    ]
